### ISSUE TITLE
Add a button on the 'Level Passed' toast

### ISSUE THREAD

**Issue by ashuvssut** [ashuvssut/the-morse-code-project#2]
![image](https://user-images.githubusercontent.com/60546840/105611444-3f02d980-5d6a-11eb-9546-3a8618d2499a.png)

after user completes a level, user should be gives option to **Play Again** and to continue to **Next Level**.

**Comment by elyskimo** [comment]
Hello, I added two buttons, I'm kinda struggling with the Sass but I think I will be able to finish the PR tonight. 

<img width="477" alt="Screenshot 2021-01-26 at 12 44 15" src="https://user-images.githubusercontent.com/33067556/105847433-e8053a80-5fdd-11eb-983b-01f040e3c7e5.png">

I used the same buttons as on the home page, I hope it's ok like this. 

This is my first contribution so  any comment or suggestion is welcome.

**Comment by ashuvssut** [comment]
Yeah Sure. I would say open a PR **now** instead. I can help you with your problems in SASS in that PR with code-reviews.

**Comment by ashuvssut** [comment]
can you add a small tooltip which appears on hovering upon the right hand side button? a small tooltip with a text 'Next Level' would be nice

It currently looks like a  'Play' button instead of 'next level'

**Comment by elyskimo** [comment]
I'm using Phpstorm code editor and I couldn't get the compilation to work.

I added an attribute title to both buttons - it works like a tooltip. 

Thank you for your fast response, I'll open a PR in a minute 😊
