### ISSUE TITLE
settings button UI

### ISSUE THREAD

**Issue by ashuvssut** [ashuvssut/the-morse-code-project#3]
# Sub task1
![image](https://user-images.githubusercontent.com/60546840/105611564-ec75ed00-5d6a-11eb-9b01-80f23ab967f6.png)
remove that small faded dot in that button

# Sub task2
![image](https://user-images.githubusercontent.com/60546840/105611591-0adbe880-5d6b-11eb-82be-ca0104cd7494.png)
make the tooltip appear under the button

**Comment by jzandag** [comment]
can you assign this to me please?

**Comment by ashuvssut** [comment]
Hi @jzandag! Please have a look on README.md before starting to contribute. See its contributing guidelines

**Comment by jzandag** [comment]
alright thanks!
